# Generated by Django 4.1.3 on 2022-11-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_forum_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
