# Generated by Django 4.1.3 on 2022-11-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_forumcomment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumcomment',
            name='down_vote',
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='up_vote',
        ),
    ]
