# Generated by Django 4.1.3 on 2022-11-10 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_forumcomment_down_vote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('up_vote', models.PositiveIntegerField()),
                ('down_vote', models.PositiveIntegerField()),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.forum')),
            ],
        ),
    ]
