# Generated by Django 4.1.3 on 2022-11-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_forumvote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcomment',
            options={'ordering': ('-created',)},
        ),
    ]
